# Generated by Django 2.1.7 on 2019-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_houses',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many houses do you own?'),
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
