# Generated by Django 2.1.7 on 2019-03-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20190321_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_of_houses',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many residences do you have?'),
        ),
    ]
