# Generated by Django 2.1.7 on 2019-03-27 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20190321_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='number_of_houses',
            new_name='number_of_residences',
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='rideshare',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transportation',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='distance_to_work',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many kilometers from your house to your workplace?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_flights',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many flights did you take last year?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_vehicles',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many vehicles do you own?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='own_summer_bike',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you own a bike that can be used when there is no snow on the ground?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='own_winter_bike',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you own a bike that can be used when there is snow on the ground?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rides_bike',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you get around on a bike?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shifts_per_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many shifts do you work per week?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='takes_public_transit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you use public transit?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='uses_rideshare',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you carpool, use taxis, or use ridesharing services?'),
        ),
        migrations.AddField(
            model_name='rideshare',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transit',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Household'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Household'),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Household'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='household',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Household'),
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
    ]
