# Generated by Django 2.1.7 on 2019-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('interview', '0007_auto_20190326_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Household',
            new_name='Residence',
        ),
        migrations.RenameField(
            model_name='appliances',
            old_name='household',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='electricity',
            old_name='household',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='naturalgas',
            old_name='household',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='trash',
            old_name='household',
            new_name='residence',
        ),
        migrations.AlterField(
            model_name='electricity',
            name='april_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in April?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='august_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in August?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='december_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in December?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='february_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in February?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='january_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in January?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='july_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in July?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='june_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in June?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='march_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in March?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='may_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in May?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='november_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in November?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='october_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in October?'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='september_electricity',
            field=models.IntegerField(verbose_name='How many kwh of electricity did your residence use in September?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='april_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in April?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='august_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in August?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='december_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in December?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='february_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in February?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='january_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in January?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='july_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in July?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='june_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in June?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='march_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in March?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='may_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in May?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='november_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in November?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='october_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in October?'),
        ),
        migrations.AlterField(
            model_name='naturalgas',
            name='september_natural_gas',
            field=models.IntegerField(verbose_name='How many GJ of natural gas did your residence use in September?'),
        ),
    ]
