# Generated by Django 2.1.7 on 2019-03-29 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_auto_20190326_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliances',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='naturalgas',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='residence',
        ),
        migrations.AddField(
            model_name='appliances',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electricity',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='naturalgas',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trash',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residence',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
