# Generated by Django 2.1.7 on 2019-04-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20190328_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliances',
            name='user',
        ),
        migrations.AddField(
            model_name='rideshare',
            name='passengers',
            field=models.IntegerField(default=0, null=True, verbose_name='How many additional passengers typically ride with you?'),
        ),
        migrations.DeleteModel(
            name='Appliances',
        ),
    ]
