# Generated by Django 2.1.7 on 2019-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_auto_20190419_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='gas_bills',
            field=models.BooleanField(null=True, verbose_name='Can you get access to your electricity bill?'),
        ),
    ]
