# Generated by Django 2.1.7 on 2019-04-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_auto_20190420_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='gas_bills',
            field=models.BooleanField(default=False, verbose_name='Can you get access to your electricity bill?'),
        ),
    ]
