# Generated by Django 2.1.7 on 2019-04-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_auto_20190420_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='housing_cost',
            field=models.IntegerField(default=1000, verbose_name='What is your monthly rent or mortgage on this property?'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='residents',
            field=models.IntegerField(default=1, verbose_name='How many people share this residence?'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='size',
            field=models.IntegerField(default=1000, verbose_name='How many square feet is this residence?'),
        ),
    ]
