# Generated by Django 2.1.7 on 2019-04-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_auto_20190420_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='able_to_move',
            field=models.BooleanField(default=False, verbose_name='Is it feasible for you to change residences in the next year or so?'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='building_type',
            field=models.CharField(choices=[('detached', 'detached house'), ('apartment', 'apartment or condo'), ('multi-unit', 'multi-unit'), ('walkup apartment', 'walk-up apartment')], default='detached', max_length=50),
        ),
        migrations.AlterField(
            model_name='residence',
            name='electricity_bills',
            field=models.BooleanField(default=False, verbose_name='Can you get access to your electricity bill?'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='owernship_type',
            field=models.CharField(choices=[('owned', 'homeowner'), ('landlord', 'renting from a private landlord or owner'), ('corporation', 'renting from a corporation or other organization'), ('family', 'living with family')], default='corporation', max_length=50),
        ),
        migrations.AlterField(
            model_name='residence',
            name='residents',
            field=models.IntegerField(default=1, verbose_name='How many people live in this residence?'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='utilities_included',
            field=models.BooleanField(default=False, verbose_name='Are utilities included in your rent?'),
        ),
    ]
