# Generated by Django 2.1.7 on 2019-04-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0015_auto_20190423_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='renewable_energy_share',
            field=models.IntegerField(default=12, verbose_name='What percentage of your energy comes from renewables?'),
        ),
    ]
