# Generated by Django 2.1.7 on 2019-05-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0016_auto_20190423_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weeks_of_vacation',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many weeks of vacation (paid and unpaid) are you entitled to per year?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shifts_per_week',
            field=models.FloatField(blank=True, null=True, verbose_name='How many shifts do you work per week?'),
        ),
    ]
